// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVIG1ZUNcrwfpW3UoOaI24CKgjGmmBhUs',
    appId: '1:584959824727:web:0b1f826d5a309052baa412',
    messagingSenderId: '584959824727',
    projectId: 'cc-caregiver-app',
    authDomain: 'cc-caregiver-app.firebaseapp.com',
    storageBucket: 'cc-caregiver-app.firebasestorage.app',
    measurementId: 'G-C8C579KZZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJrs4_RjyOTrgpz6AwSxb_-arT5NqcKk',
    appId: '1:584959824727:android:1df7a71455c38ffbbaa412',
    messagingSenderId: '584959824727',
    projectId: 'cc-caregiver-app',
    storageBucket: 'cc-caregiver-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdDHgnZAf54sAag4c8KycUFhKOSHeWqM',
    appId: '1:584959824727:ios:3559d7afc9f3ab96baa412',
    messagingSenderId: '584959824727',
    projectId: 'cc-caregiver-app',
    storageBucket: 'cc-caregiver-app.firebasestorage.app',
    iosBundleId: 'com.example.healthcare.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdDHgnZAf54sAag4c8KycUFhKOSHeWqM',
    appId: '1:584959824727:ios:3559d7afc9f3ab96baa412',
    messagingSenderId: '584959824727',
    projectId: 'cc-caregiver-app',
    storageBucket: 'cc-caregiver-app.firebasestorage.app',
    iosBundleId: 'com.example.healthcare.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVIG1ZUNcrwfpW3UoOaI24CKgjGmmBhUs',
    appId: '1:584959824727:web:765d5fda6407d948baa412',
    messagingSenderId: '584959824727',
    projectId: 'cc-caregiver-app',
    authDomain: 'cc-caregiver-app.firebaseapp.com',
    storageBucket: 'cc-caregiver-app.firebasestorage.app',
    measurementId: 'G-RDZVXFVTPR',
  );
}
